### PR TITLE
Updates selenium-standalone-server to v3.8.1. Also updates Mocha and ChaiJS to recent versions

### PR DESCRIPTION
**Pull request by mAiNiNfEcTiOn**
# What does this PR do:

* Updates mocha and chai to more recent versions.
* Updates selenium-server-standalone to version 3.8.1

### CODE REVIEW

**Comment by adamhooper** [comment]
Thank you!

**Comment by mAiNiNfEcTiOn** [comment]
@adamhooper you're welcome sir. Thank you for this repo 👍  and for merging my PR!

**Comment by mAiNiNfEcTiOn** [comment]
@adamhooper don't forget to release it on NPM though. Thanks! 👍

**Comment by adamhooper** [comment]
D'oh! Thanks for the reminder. It's live now.

**Pull request merged**
